-- Create the narrative_forms table if it doesn't exist
CREATE TABLE IF NOT EXISTS `narrative_forms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ppas_id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `implementing_office` varchar(255) NOT NULL,
  `partner_agency` varchar(255) DEFAULT NULL,
  `service_agenda` text DEFAULT NULL,
  `sdg` text DEFAULT NULL,
  `beneficiaries` text DEFAULT NULL,
  `tasks` text DEFAULT NULL,
  `general_objective` text NOT NULL,
  `specific_objective` text NOT NULL,
  `activity_title` varchar(255) NOT NULL,
  `activity_narrative` text NOT NULL,
  `evaluation_result` text NOT NULL,
  `survey_result` text NOT NULL,
  `photos` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ppas_id` (`ppas_id`),
  KEY `username` (`username`),
  CONSTRAINT `narrative_forms_ibfk_1` FOREIGN KEY (`ppas_id`) REFERENCES `ppas_forms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 